
stages:
  - build
  - build_image

build:
  stage: build
  script: 
    - mvn clean compile package

build_image:
  stage: build_image
  script:
    - cp -R speedy-protal/target/speedy-protal-0.0.2/* /root/springboot-docker/working/
    - cd /root/springboot-docker
    - docker build -t my/springboot .
